import React from 'react';
import { Link } from 'react-router-dom';
import { ChevronLeftIcon, FileTextIcon } from 'lucide-react';
import s from './LegalLayout.module.css';

export default function TermsOfService() {
  return (
    <div className={s.container}>
      {/* Background decorations */}
      <div className={s.ambientBg}>
        <div className={s.blob1} />
        <div className={s.blob2} />
      </div>

      <nav className={s.nav}>
        <Link to="/builder" className={s.backBtn}>
          <ChevronLeftIcon size={16} />
          Back to Volturiano Builder
        </Link>
      </nav>

      <main className={s.content}>
        <header className={s.header}>
          <div className={s.iconWrapper}>
            <FileTextIcon size={32} className={s.icon} />
          </div>
          <h1 className={s.title}>Terms of Service</h1>
          <p className={s.lastUpdated}>Last updated: March 2026</p>
        </header>

        <section className={s.section}>
          <h2>1. Introduction</h2>
          <p>
            Welcome to Volturiano. By accessing or using our Website and Builder platform, you agree to be bound by these Terms of Service. 
            If you do not agree to all the terms and conditions, then you may not access the website or use any services.
          </p>
        </section>

        <section className={s.section}>
          <h2>2. Service Description</h2>
          <p>
            Volturiano is an AI-powered website builder platform that generates frontend code, components, and entire sites based on user prompts. 
            You must be at least 18 years old to use our services and create an account.
          </p>
        </section>

        <section className={s.section}>
          <h2>3. User Accounts and Obligations</h2>
          <p>
            When you create an account, you must provide accurate and complete information. You are solely responsible for the activity that occurs on your account and you must keep your account password secure. you must immediately notify us of any breach of security or unauthorized use of your account.
          </p>
          <p>You agree not to use the service for any illegal or unauthorized purpose, including but not limited to:</p>
          <ul>
            <li>Generating or publishing content that is unlawful, harmful, threatening, abusive, or harassing.</li>
            <li>Generating or publishing content that infringes upon a third party's intellectual property rights.</li>
            <li>Uploading malicious code, viruses, or deploying bots to scrape our systems.</li>
            <li>Attempting to bypass our AI credit systems, payment systems, or rate limiting mechanisms.</li>
          </ul>
        </section>

        <section className={s.section}>
          <h2>4. Billing, Credits & Refunds</h2>
          <p>
            Volturiano operates on a subscription and virtual credit system. Virtual credits are used to generate websites and components via AI models.
          </p>
          <ul>
            <li><strong>Purchases:</strong> All purchases through Stripe are final. When a payment goes through, the corresponding credits are added to your account instantly.</li>
            <li><strong>No Refunds:</strong> Due to the immediate consumptive nature of AI APIs, we do not offer refunds on used or partially used credit packs.</li>
            <li><strong>Subscriptions:</strong> Should you cancel a subscription, your plan will remain active until the end of your billing cycle. Unused monthly credits will expire if you do not renew.</li>
          </ul>
        </section>

        <section className={s.section}>
          <h2>5. User Generated Content & Intellectual Property</h2>
          <p>
            Any code generated by the Volturiano Builder relying on user prompts is intended for your use. You retain all rights to the final code exported from your projects.
          </p>
          <p>
            However, any community templates or components you submit to the Volturiano Community Hub are subject to review. By submitting them, you grant us a worldwide, non-exclusive, royalty-free license to use, reproduce, modify, and distribute the component on the Volturiano platform.
          </p>
        </section>

        <section className={s.section}>
          <h2>6. Limitation of Liability</h2>
          <p>
            Volturiano, its directors, employees, partners, agents, suppliers, or affiliates, shall not be liable for any indirect, incidental, special, consequential or punitive damages, including without limitation, loss of profits, data, use, goodwill, or other intangible losses, resulting from (i) your access to or use of or inability to access or use the Service; (ii) any conduct or content of any third party on the Service; (iii) any content obtained from the Service; and (iv) unauthorized access, use or alteration of your transmissions or content.
          </p>
        </section>

        <section className={s.section}>
          <h2>7. Termination</h2>
          <p>
            We may terminate or suspend your account immediately, without prior notice or liability, for any reason whatsoever, including without limitation if you breach the Terms. Upon termination, your right to use the Service will immediately cease. If you wish to terminate your account, you may simply discontinue using the Service or use the "Delete Account" feature in your dashboard.
          </p>
        </section>

        <section className={s.section}>
          <h2>8. Governing Law</h2>
          <p>
            These Terms shall be governed and construed in accordance with the laws of Sweden, without regard to its conflict of law provisions. Any disputes arising out of these Terms will be handled in Swedish courts.
          </p>
          <p>
            Our failure to enforce any right or provision of these Terms will not be considered a waiver of those rights.
          </p>
        </section>
      </main>
    </div>
  );
}
